```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
opts_chunk$set(comment = "", error= TRUE, warning = FALSE, message = FALSE,
               tidy = FALSE, cache = TRUE, echo = T,
               fig.width = 6, fig.height = 6)
```
Testing Test

========================================================

```{r}
set.seed(101)

# Read Data

size <- 50
my.data <- data.frame(x1 <- rpois(size,4),
                      x2 <- rnorm(size,10),
                      x3 <- rpois(size,20),
                      x4 <- rnorm(size,4,1),                      
                      y <- x4^2*x2 + x1^2*x3 + 5)

# Preprocess Data

names(my.data) <- c(paste0("x",1:(ncol(my.data)-1)),"y")

sapply(my.data, class)
my.data$x1 <- as.numeric(my.data$x1) # x1 becomes a numeric value
head(my.data,8)

# Execute ML methods

source("gapolyfuncs.R")
report <- make.report(my.data, population=50, iterations=25, mutation.rate=0.05, runs=1)

# See Results

coef(report$ga.model)
report$ga.error

# boxplot(report$ga.error, 
#         report$lm.error,
#         report$svm.error,
#         report$rpart.error,
#         report$rf.error,
#         report$citree.error,
#         names=c("GA Poly", "Lin.Reg.", "SVM", "RPART", "Rnd.For.", "CI Tree"),
#         ylab="RMSE")

# df <- data.frame(GA.Poly = report$ga.error,
#                  Lin.Reg = report$lm.error,
#                  SVM = report$svm.error,
#                  RPART = report$rpart.error,
#                  Rnd.For = report$rf.error,
#                  CI.Tree = report$citree.error)
# 
# write.table(df, "Articial_dataset.txt")

size <- length(report$ga.error)
list.data <- list(error=c(report$ga.error, 
                          report$lm.error,
                          report$svm.error,
                          report$rpart.error,
                          report$rf.error,
                          report$citree.error), 
                  method=c(rep("GA.Poly",size),
                           rep("Lin.Reg.",size),
                           rep("SVM",size), 
                           rep("RPART",size),
                           rep("Rnd.For.",size),
                           rep("CI.Tree",size)))

df <- as.data.frame(list.data)

library(ggplot2)
qplot(method,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("regression method") +
  ggtitle("Artificial dataset")

##############################################

# Lambda Test
lambda.values <- seq(1,2,length.out=20)
n.runs <- 1

source("gapolyfuncs.R")
errors <- test.lambda(my.data, lambda.values, runs=n.runs, population=10, iterations=10)

# df <- as.data.frame(errors)
# names(df) <- round(lambda.values,3)

df <- data.frame(error = as.vector(matrix(errors,nrow=1)),
                 lambda = as.factor(rep(round(lambda.values,3), each=n.runs)))

write.table(df, "lambda.errors.txt")

library(ggplot2)
qplot(lambda,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("lambda value") +
  coord_cartesian(ylim = c(0, 50))  +
  ggtitle("Artificial dataset")

library(plyr)
best.errors <- 
  colwise(function(x) min(as.numeric(x)))(as.data.frame(errors)) # get min for each column

plot(lambda.values, best.errors, type="l")
##############################################
# Check fitness progress

source("gapolyfuncs.R")
follow.fitness(my.data,population=200,iterations=50)

# output:

progress <- c(78.3925,78.3925,71.30467,71.30467,60.09713,20.41959,15.00416,15.00416,15.00416,15.00416,15.00416,15.00416,12.31946,12.31946,12.31946,12.31946,2.971683,2.971683,2.971683,2.971683,6.569273e-14,6.569273e-14,6.500183e-14,6.500183e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14,3.573077e-14)

df <- data.frame(iteration = 1:length(progress),
                 fitness = as.numeric(progress))

qplot(iteration, fitness, data=df) +
  geom_line() +
  ylim(0, max(df$fitness)) +
  ggtitle("Artificial dataset (population 200)")

##############################################
# print(xtable(res.df), include.rownames = FALSE, floating = FALSE, type = "latex")
```
