```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
opts_chunk$set(comment = "", error= TRUE, warning = FALSE, message = FALSE,
               tidy = FALSE, cache = TRUE, echo = T,
               fig.width = 6, fig.height = 6)
```
Testing Auto-Mpg
========================================================

```{r}
set.seed(101)

# Read Data

filename <- "Auto-Mpg/auto.data"  # where is the data (under dataset folder)
filepath <- paste0("datasets/",filename)
my.data <- read.csv(filepath, header=FALSE)

# Preprocess Data

# my.data <- na.omit(my.data) # the dataset has some NAs

names(my.data) <- c(paste0("x",1:(ncol(my.data)-1)),"y")

sapply(my.data, class)
my.data$x3 <- as.numeric(my.data$x3) # x3 was a factor, make it a numeric value
my.data <- as.data.frame(scale(my.data)) # scale it
head(my.data,8)

# Execute ML methods

source("gapolyfuncs.R")
report <- make.report(my.data, population=300, iterations=100, lambda=0.8, runs=25)


load(file="Auto-Mpg300_lambda0.8_add_linears.Rda")
load(file="Auto-Mpg300_lambda1_allmonoids.Rda")
summary(report$ga.error)

# See Results

save(report, file="Auto-Mpg300_lambda0.8_add_linears.Rda") # recover with load("Auto-Mpg300.Rda") 

coef(report$ga.model)
report$ga.error

library(ggplot2)

df <- data.frame(GA.Poly = report$ga.error,
                 Lin.Reg = report$lm.error,
                 SVM = report$svm.error,
                 RPART = report$rpart.error,
                 Rnd.For = report$rf.error,
                 CI.Tree = report$citree.error)

write.table(df, "Auto-Mpg300_lambda0.8_add_linears.txt")

size <- length(report$ga.error)
list.data <- list(error=c(report$ga.error, 
                          report$lm.error,
                          report$svm.error,
                          report$rpart.error,
                          report$rf.error,
                          report$citree.error), 
                  method=c(rep("GA.Poly",size),
                           rep("Lin.Reg.",size),
                           rep("SVM",size), 
                           rep("RPART",size),
                           rep("Rnd.For.",size),
                           rep("CI.Tree",size)))

df <- as.data.frame(list.data)

qplot(method,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("regression method") +
  ggtitle("Auto-Mpg dataset")

########################################################
# Lambda Test
lambda.values <- seq(0.7,1.3,by=0.05)
n.runs <- 10

source("gapolyfuncs.R")
errors <- test.lambda(my.data, lambda.values, runs=n.runs, population=60, iterations=60)

df <- data.frame(error = as.vector(matrix(errors,nrow=1)),
                 lambda = as.factor(rep(round(lambda.values,3), each=n.runs)))

write.table(df, "lambda.errors.Auto-Mpg.txt")

df <- read.table("lambda.errors.Auto-Mpg.txt", header=TRUE)


df$lambda <- as.factor(df$lambda)

library(ggplot2)
qplot(lambda,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("lambda value") +
 # coord_cartesian(ylim = c(0, 50))  +
  ggtitle("Auto-Mpg dataset")
##############################################
# Check fitness progress

source("gapolyfuncs.R")
follow.fitness(my.data,population=300,iterations=50,mutation.rate=0.15,lambda=0.95)

########################################################
# Tuning SVM & RPART

rsme <- function(v1, v2=c(0)) {
  sqrt(mean((v1-v2)^2))
}

library(e1071)

head(my.data,8)

n.runs <- 25
train.p.size <- 0.7 # percentage of training set

svm.error <- rep(NA,n.runs)
rpart.error <- rep(NA,runs)

for (i in 1:n.runs) {
  inTrain   <- sample(1:nrow(my.data), train.p.size * nrow(my.data))
  train.set <- my.data[inTrain,]
  test.set  <- my.data[-inTrain,]

  svm.tune <- tune.svm(y ~ ., data=train.set)
  svm.pred  <- predict(svm.tune$best.model, test.set[,-ncol(test.set)]) 
  svm.error[i] <- rsme(svm.pred,test.set[,ncol(test.set)])
  
  rpart.tune <- tune.rpart(y ~ ., data=train.set)
  rpart.pred  <- predict(rpart.tune$best.model, test.set[,-ncol(test.set)]) 
  rpart.error[i] <- rsme(rpart.pred,test.set[,ncol(test.set)])
}


########################################################

# print(xtable(res.df), include.rownames = FALSE, floating = FALSE, type = "latex")
```

