```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
opts_chunk$set(comment = "", error= TRUE, warning = FALSE, message = FALSE,
               tidy = FALSE, cache = TRUE, echo = T,
               fig.width = 6, fig.height = 6)
```
Testing Abalone
========================================================

This is a template for testing purposes.

```{r}
set.seed(101)

# Read Data

filename <- "Abalone/abalone.data"  # where is the data (under dataset folder)
filepath <- paste0("datasets/",filename)
my.data  <- read.csv(filepath)

# Preprocess Data

# This would be the variables names and output ("rings") 
#   names(my.data) <- c("sex","length","diameter","height","whole.weight","shucked.weight","viscera.weight","shell.weight","rings")
# but we must name them as x_i and y:
names(my.data) <- c(paste0("x",1:8),"y")
my.data$x1 <- as.numeric(my.data$x1) # x1 was a factor, make it a numeric value
head(my.data,8)
my.data <- as.data.frame(scale(my.data))

# Execute ML methods

source("gapolyfuncs.R")
report <- make.report(my.data, population=300, iterations=100, lambda=1, runs=25)

# See Results

coef(report$ga.model)
report$ga.error

save(report, file="Abalone300_lambda1_allmonoids.Rda") # recover with load("Abalone.Rda") 

df <- data.frame(ga.poly = report$ga.error, 
                 lin.reg = report$lm.error,
                 svm = report$svm.error,
                 rpart = report$rpart.error,
                 rf = report$rf.error,
                 ci.tree = report$citree.error)

write.table(df, "Abalone300_lambda1_allmonoids.txt")

library(ggplot2)

size <- length(report$ga.error)
list.data <- list(error=c(report$ga.error, 
                          report$lm.error,
                          report$svm.error,
                          report$rpart.error,
                          report$rf.error,
                          report$citree.error), 
                  method=c(rep("GA.Poly",size),
                           rep("Lin.Reg.",size),
                           rep("SVM",size), 
                           rep("RPART",size),
                           rep("Rnd.For.",size),
                           rep("CI.Tree",size)))

df <- as.data.frame(list.data)

qplot(method,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("regression method") +
  ggtitle("Abalone dataset")
  
##############################################
# Lambda Test
lambda.values <- seq(0.7,1.3,by=0.05)
n.runs <- 5

source("gapolyfuncs.R")
errors <- test.lambda(my.data, lambda.values, runs=n.runs, population=50, iterations=60)

# df <- as.data.frame(errors)
# names(df) <- round(lambda.values,3)

df <- data.frame(error = as.vector(matrix(errors,nrow=1)),
                 lambda = as.factor(rep(round(lambda.values,3), each=n.runs)))

write.table(df, "Abalone_lambda.errors.txt")

library(ggplot2)
qplot(lambda,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("lambda value") +
  coord_cartesian(ylim = c(2, 3))  +
  ggtitle("Abalone dataset")

library(plyr)
best.errors <- 
  colwise(function(x) min(as.numeric(x)))(as.data.frame(errors)) # get min for each column

plot(lambda.values, best.errors, type="l")

##############################################
# Check fitness progress

source("gapolyfuncs.R")
follow.fitness(my.data,population=200,iterations=250,mutation.rate=0.15,lambda=1.0)

# output:

lambda0.975 <- c(2.473536,2.414038,2.414038,2.414038,2.406747,2.406747,2.316709,2.350614,2.330452,2.313667,2.251034,2.251034,2.251034,2.275441,2.275441,2.275441,2.275307,2.275307,2.275307,2.268287,2.268287,2.268287,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.225473,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.200263,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951,2.184951)

lambda1.0 <- c(2.459798,2.391793,2.391793,2.391793,2.391793,2.391793,2.330641,2.330641,2.330641,2.317893,2.317893,2.317893,2.317893,2.317893,2.317893,2.317893,2.317893,2.295766,2.295766,2.295766,2.295766,2.295766,2.295766,2.295766,2.295766,2.295766,2.295766,2.295766,2.268242,2.268242,2.268242,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.260962,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.247364,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.238047,2.221251,2.221251)

df <- data.frame(iteration = 1:length(lambda0.975),
                 lambda0.975 = as.numeric(lambda0.975),
                 lambda1.0 = as.numeric(lambda1.0))

ggplot(df, aes(iteration)) + 
  geom_line(aes(y = lambda0.975, colour = "lambda = 0.975")) + 
  geom_line(aes(y = lambda1.0, colour = "lambda = 1.0")) +
  ylim(2.15, 2.5) +
  ggtitle("Abalone dataset (population 200)") +
  ylab("rmse") + 
  theme(legend.title=element_blank()) # remove legend title
```

