```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
opts_chunk$set(comment = "", error= TRUE, warning = FALSE, message = FALSE,
               tidy = FALSE, cache = TRUE, echo = T,
               fig.width = 6, fig.height = 6)
```
Testing Ailerons
========================================================

```{r}
source("gapolyfuncs.R")

set.seed(101)

# Read Data

filename <- "Ailerons/ailerons"  # where is the data (under dataset folder)
filepath <- paste0("datasets/",filename)
my.data <- read.csv(filepath)

# Preprocess Data

my.data <- na.omit(my.data) # the dataset has some NAs
my.data <- my.data[,c(1:25,27:41)] # x26 is almost all zeros

names(my.data) <- c(paste0("x",1:(ncol(my.data)-1)),"y")

sapply(my.data, class)
my.data$x1 <- as.numeric(my.data$x1) # x1 was a factor, make it a numeric value
head(my.data,8)

# Execute ML methods

source("gapolyfuncs.R")
report <- make.report(my.data, population=200, iterations=200)

# See Results

coef(report$ga.model)
report$ga.error

boxplot(report$ga.error, 
        report$lm.error,
        report$svm.error,
        report$rpart.error,
        report$rf.error,
        report$citree.error,
        names=c("GA Poly", "Lin.Reg.", "SVM", "RPART", "Rnd.For.", "CI Tree"),
        ylab="RMSE")

df <- data.frame(ga.poly = report$ga.error, 
                 lin.reg = report$lm.error,
                 svm = report$svm.error,
                 rpart = report$rpart.error,
                 rf = report$rf.error,
                 ci.tree = report$citree.error)

save(report, file="Ailerons.Rda") # recover with load("Ailerons.Rda") 

write.table(df, "Ailerons.txt")

# print(xtable(res.df), include.rownames = FALSE, floating = FALSE, type = "latex")
```

Tabela para Ailerons dataset
------

