```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
opts_chunk$set(comment = "", error= TRUE, warning = FALSE, message = FALSE,
               tidy = FALSE, cache = TRUE, echo = T,
               fig.width = 6, fig.height = 6)
```
Testing Housing
========================================================

```{r}
set.seed(321)

# Read Data

filename <- "Housing/housing.data"  # where is the data (under dataset folder)
filepath <- paste0("datasets/",filename)
my.data <- read.csv(filepath, header=FALSE)

# Preprocess Data

# my.data <- na.omit(my.data) # the dataset has some NAs

names(my.data) <- c(paste0("x",1:(ncol(my.data)-1)),"y")

sapply(my.data, class)
# my.data$x3 <- as.numeric(my.data$x3) # x3 was a factor, make it a numeric value
head(my.data,8)
my.data <- as.data.frame(scale(my.data))

# Execute ML methods

source("gapolyfuncs.R")
report <- make.report(my.data, population=300, iterations=100, lambda=0.8, runs=25)

# See Results

save(report, file="Housing300_lambda0.8_add_linears.Rda") # recover with load("Housing300.Rda") 

load(file="Housing300_lambda0.8_add_linears.Rda")

load(file="Housing300_lambda1_allmonoids.Rda")



summary(report$ga.error)


coef(report$ga.model)
report$ga.error


df <- data.frame(GA.Poly = report$ga.error,
                 Lin.Reg = report$lm.error,
                 SVM = report$svm.error,
                 RPART = report$rpart.error,
                 Rnd.For = report$rf.error,
                 CI.Tree = report$citree.error)

write.table(df, "Housing300_lambda0.8_add_linears.txt")

library(ggplot2)
size <- length(report$ga.error)
list.data <- list(error=c(report$ga.error, 
                          report$lm.error,
                          report$svm.error,
                          report$rpart.error,
                          report$rf.error,
                          report$citree.error), 
                  method=c(rep("GA.Poly",size),
                           rep("Lin.Reg.",size),
                           rep("SVM",size), 
                           rep("RPART",size),
                           rep("Rnd.For.",size),
                           rep("CI.Tree",size)))

df <- as.data.frame(list.data)

qplot(method,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("regression method") +
  coord_cartesian(ylim = c(0.2, 0.75))  +
  ggtitle("Housing dataset")


########################################################
# Compare versions of GA.Poly (with vs without regularization)
set.seed(765)
source("gapolyfuncs.R")
report <- test.regularization(my.data, population=300, iterations=75, lambda=0.01, runs=10)

save(report, file="Housing300_lambda0.01.vs.no.reg2_2.Rda")  
# report <- load("Housing300_lambda0.01.vs.no.reg2_1.Rda")  # recover with

df <- data.frame(GA.Poly = report$ga.error,
                 GA.Poly.reg = report$ga.reg.error)

write.table(df, "Housing300_lambda0.01.vs.no.reg2_2.txt")

########################################################
# Lambda Test (1st variant of regularization)
lambda.values <- seq(0.5,0.999,length.out=20)
n.runs <- 5

source("gapolyfuncs.R")
errors <- test.lambda(my.data, lambda.values, runs=n.runs, population=50, iterations=25)

df <- data.frame(error = as.vector(matrix(errors,nrow=1)),
                 lambda = as.factor(rep(round(lambda.values,3), each=n.runs)))

write.table(df, "lambda.errors.Housing.txt")

df <- read.table("lambda.errors.Housing.txt", header=TRUE)

df$lambda <- as.factor(df$lambda)

library(ggplot2)
qplot(lambda,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("lambda value") +
 # coord_cartesian(ylim = c(0, 50))  +
  ggtitle("Housing dataset")

########################################################
# Lambda Test (2nd variant of regularization)
size <- 20
lambda.values <- rep(NA, size)

val <- 0.003
for(i in 1:size) {
  lambda.values[i] = val
  val = val * 2^(1/3)  # duplicate every three steps
}

n.runs <- 10

source("gapolyfuncs.R")
errors <- test.lambda(my.data, lambda.values, runs=n.runs, population=50, iterations=40)

df <- data.frame(error = as.vector(matrix(errors,nrow=1)),
                 lambda = as.factor(rep(round(lambda.values,3), each=n.runs)))

write.table(df, "lambda.errors.Housing.txt")

df <- read.table("lambda.errors.Housing.txt", header=TRUE)

df$lambda <- as.factor(df$lambda)

library(ggplot2)
qplot(lambda,error,data=df,geom=c("jitter","boxplot")) + 
  ylab("root-mean-square error") + 
  xlab("lambda value") +
 # coord_cartesian(ylim = c(0, 50))  +
  ggtitle("Housing dataset")


##############################################
# Check fitness progress

source("gapolyfuncs.R")
follow.fitness(my.data,population=300,iterations=50,mutation.rate=0.15,lambda=0.95)

########################################################
# check what attributes Random Forest select as the most importants

train.p.size <- 0.7 # percentage of training set
n.vars       <- ncol(my.data)-1

inTrain   <- sample(1:nrow(my.data), train.p.size * nrow(my.data))
train.set <- my.data[inTrain,]
test.set  <- my.data[-inTrain,]

rf.model <- randomForest(y ~ ., data=train.set, importance=TRUE, do.trace=100, ntree=100)
rf.model$importance




# print(xtable(res.df), include.rownames = FALSE, floating = FALSE, type = "latex")
```
